---
- name: Check Centos Version
  assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version | int >= 7
      - ansible_distribution_major_version | int <= 9
    fail_msg: 'This role supports Centos 7 or 8'

- name: Fastest Mirror Tuning
  become: true
  copy:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    content: |
      [main]
      enabled=1
      verbose=0
      always_print_best_host = true
      socket_timeout=1
      #  Relative paths are relative to the cachedir (and so works for users as well
      # as root).
      hostfilepath=timedhosts.txt
      maxhostfileage=10
      maxthreads=500

- name: Wait for Centos to be accessible - eg just started containers networking can take a few seconds
  become: true
  wait_for:
    host: mirrorlist.centos.org
    port: 80
    delay: 0
    sleep: 2
    timeout: 30
    state: started

- name: Update installed packages
  become: true
  package:
    name: "*"
    state: latest
  when: lts_centos_update_packages

- name: Add EPEL
  become: true
  package:
    name: epel-release
    state: latest

- name: Basic packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - wget
      - bash-completion
      - sudo
      - python3
      - htop
      - man

- name: Centos 7 Packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - policycoreutils-python
      - bash-completion-extras
  when: ansible_distribution_major_version | int == 7

- name: Centos 8 Packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - policycoreutils-python-utils
      - hostname
  when: ansible_distribution_major_version | int == 8

- name: Bash Profile
  become: true
  copy:
    src: ./../templates/etc/profile.d/zz_lts.sh
    dest: /etc/profile.d/zz_lts.sh

- name: Vim Config
  become: true
  copy:
    src: ./../templates/etc/vimrc
    dest: /etc/vimrc

- name: Vim colour scheme
  become: true
  copy:
    src: ./../templates/usr/share/vim/vimfiles/colors/deus.vim
    dest: /usr/share/vim/vimfiles/colors/deus.vim

- name: Locale
  become: true
  copy:
    content: |
      LANG=en_GB.utf8
      export LANG
      LC_ALL=en_GB.UTF-8
      export LC_ALL
    dest: /etc/profile.d/zz_locale.sh

- name: set Timezone to Europe/London
  become: true
  timezone:
    name: Europe/London

- name: Passwordless Wheel Sudo
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^.+?%wheel"
    line: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'
  when: lts_centos_sudo_wheel

- name: Set hostname to match ansible hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  # XXX: defaults to hostnamectl, but that will fail when systemd is not running,
  # including containers (like docker) that do not run systemd by default
  ignore_errors: true
